kind: Secret
apiVersion: v1
metadata:
  name: thanos-objectstorage
  namespace: thanos
data:
  thanos.yaml: >-
    dHlwZTogUzMKY29uZmlnOgogIGJ1Y2tldDogInRoYW5vcyIKICBlbmRwb2ludDogIm1pbmlvLW15LXN0b3JlLnJvb2stbWluaW86OTAwMCIKICByZWdpb246ICJkZWZhdWx0IgogIGFjY2Vzc19rZXk6ICJURU1QX0RFTU9fQUNDRVNTX0tFWSIKICBpbnNlY3VyZTogdHJ1ZQogIHNpZ25hdHVyZV92ZXJzaW9uMjogdHJ1ZQogIGVuY3J5cHRfc3NlOiBmYWxzZQogIHNlY3JldF9rZXk6ICJURU1QX0RFTU9fU0VDUkVUX0tFWSIKICBwdXRfdXNlcl9tZXRhZGF0YToge30KICBodHRwX2NvbmZpZzoKICAgIGlkbGVfY29ubl90aW1lb3V0OiA5MHMKICAgIHJlc3BvbnNlX2hlYWRlcl90aW1lb3V0OiAybQogICAgaW5zZWN1cmVfc2tpcF92ZXJpZnk6IHRydWUKICB0cmFjZToKICAgIGVuYWJsZTogdHJ1ZQogIHBhcnRfc2l6ZTogMTM0MjE3NzI4ICAgCg==
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-self
  namespace: thanos
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-self
  namespace: thanos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-self
subjects:
- kind: ServiceAccount
  name: default
  namespace: thanos
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: self
  namespace: thanos
  labels:
    prometheus: self
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  thanos:
    version: v0.10.1
    objectStorageConfig:
      name: thanos-objectstorage
      key: thanos.yaml
      optional: true
  disableCompaction: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    prometheus: self
  name: prometheus-self
  namespace: thanos
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: self
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  namespace: thanos
  labels:
    app: thanos-sidecar
spec:
  clusterIP: None
  selector:
    prometheus: self
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc